### ISSUE TITLE
Not installable via `pip`

### ISSUE THREAD

**Issue by zachriggle** [programa-stic/barf-project#12]
Currently there's no way to make the BARF project available to another project as a requirement via PyPI, or to install it for use via `pip`.  The process is generally painless.

Both pybfd and capstone are available by via `pip install`, so those dependencies can be automatically installed.  Z3 is not yet available in this manner, but I've opened an issue with the project to make it available.  In any case, it can be left as a manual dependency.

Would you be interested in implementing this functionality to make BARF more easily usable from external projects?  In particular, I'm looking at integrating it with [binjitsu](https://binjit.su).

**Comment by neuromancer** [comment]
Hello,

I did a very simple script to install barf locally (using "python setup.py --user"). It is available [here](https://github.com/cnheitman/barf-project/blob/develop/barf/local.install.sh). If you are particulary interested, i can work on a "pip install" equivalent and ask @cnheitman to integrate it in the main BARF repository..

**Comment by zachriggle** [comment]
The local-install script is a useful starting point, but realistically I need BARF to get pulled in and installed automatically by pip.

**Comment by cnheitman** [comment]
Hi! Yes, installation via ``pip`` would be a useful feature. I can work on that (or accept a pull request
in case @neuromancer develop it first.)
