### ISSUE TITLE
Move pyasmjit to a separate project/repo

### ISSUE THREAD

**Issue by adrianherrera** [programa-stic/barf-project#17]
Hi,

Is it possible to move pyasmjit to a separate project/repo outside of the barf-project repo? I am interested in experimenting with pyasmjit as a stand-alone library (i.e. without the entire barf dependency) and extending its functionality. Having pyasmjist exist as a separate entity would greatly simplify this.

Many thanks.

Regards,
Adrian

**Comment by cnheitman** [comment]
Hi!

Yes, it is possible to make a separate repo for PyAsmJIT. I haven't done it so far because, currently, the only use I gave it was for BARF. However, I think it can be an interesting project on its own.

A couple of questions: 
 - Just out of curiosity, what are you using it for? 
 - What functionalities are you planning to implement? I love pull requests :)

Cheers!
Christian

**Comment by adrianherrera** [comment]
Hi Christian,

Yes, I think it can be a very cool project on its own. And separating it out also allows it to be pip installable, etc.

* I really just want to use it as a tool where I can extract fragments of code from an application and experiment with these fragments by varying the inputs and reasoning about the code
* I'm currently looking at implementing a lot of the missing functionality that has already been flagged - support for 32-bit X86, allowing access to memory, etc.. You will probably start getting a large number of pull requests from me very soon :-)

Regards,
Adrian

**Comment by cnheitman** [comment]
Hi Adrian,

It would be great to have those functionalities implemented and, also, make it pip installable!

So, I will move it to its own repo. Most probably I will get it done by Monday. I let 
you known when its done.

Cheers,
Christian

**Comment by cnheitman** [comment]
Well, I finally did it! You can clone it from: https://github.com/programa-stic/pyasmjit

I have to clean up the barf-project repo now but it shouldn't affect you.

**Comment by adrianherrera** [comment]
Thanks Christian!
