### ISSUE TITLE
Unable to open PE files

### ISSUE THREAD

**Issue by chubbymaggie** [programa-stic/barf-project#20]
Hi,

I am unable to load pe files. The reason is that `pe.sections[section_idx].get_data()`  always returns null. But after going through `pefile` library, I fixed the problem by givng the virtualaddress as the parameter for `get_data()`.  
This is the fix:
`self._section_text = pe.sections[section_idx].get_data(pe.sections[section_idx].VirtualAddress)`

This hack works fine for me now . I don't know whether this is correct?

Thanks.

Regards,
Maggie

**Comment by cnheitman** [comment]
Hi,

I try it with several PE files an I couldn't reproduce your problem. Also, I check what was
load
