### ISSUE TITLE
Gadget not correctly verified?

### ISSUE THREAD

**Issue by ejohn** [programa-stic/barf-project#24]
Is there a reason why the following assembly code would not be a valid store memory gadget? The classification stage picked it up but it does not verify as a valid store memory gadget. Is this a bug or am I missing something?

```
mov dword ptr [rax], esi ; ret 
```

**Comment by cnheitman** [comment]
Hi,

No, it should be verified correctly. I pushed a test with that particular piece of code.
You can see it, [here](https://github.com/programa-stic/barf-project/blob/master/barf/tests/analysis/gadget/test_gadget_x86.py#L1529). Check if the passes and let me know.

Cheers,
Christian

**Comment by ejohn-si** [comment]
The gadget is being correctly verified now.

**Comment by ejohn** [comment]
The gadget is being correctly verified now.
