### ISSUE TITLE
Details are unavailable (CS_ERR_DETAIL)

### ISSUE THREAD

**Issue by abforce** [programa-stic/barf-project#33]
I've installed BARF but I'm not sure if it's installed correctly. I run the following code for a binary shared object file (`.so`), but it encounters an error while it's translating.

    from barf import BARF

    # Open binary file.
    barf = BARF('bin/tests/test1.so')

    # Print assembly instruction.
    for addr, asm_instr, reil_instrs in barf.translate():
        print("0x{addr:08x} {instr}".format(addr=addr, instr=asm_instr))

        # Print REIL translation.
        for reil_instr in reil_instrs:
            print("{indent:11s} {instr}".format(indent="", instr=reil_instr))

Output:

    Couldn't import dot_parser, loading of dot files will not be possible.
    0x00000e98 moval r4, r0
                str   [DWORD r0, EMPTY, DWORD r4]
                and   [DWORD r0, DWORD 0xffffffff, DWORD t1]
                bisz  [DWORD t1, EMPTY, BIT zf]
                bsh   [DWORD r0, DWORD 0xffffffe1, DWORD t2]
                and   [DWORD t2, DWORD 0x1, BIT t3]
                str   [BIT t3, EMPTY, BIT nf]
    0x00000e9a bal #0x9dc
                jcc   [BIT 0x1, EMPTY, POINTER 0x9dc00]
    0x00000e9c moval r0, r0
                str   [DWORD r0, EMPTY, DWORD r0]
                and   [DWORD r0, DWORD 0xffffffff, DWORD t4]
                bisz  [DWORD t4, EMPTY, BIT zf]
                bsh   [DWORD r0, DWORD 0xffffffe1, DWORD t5]
                and   [DWORD t5, DWORD 0x1, BIT t6]
                str   [BIT t6, EMPTY, BIT nf]
    0x00000e9e bal #0xfc0
                jcc   [BIT 0x1, EMPTY, POINTER 0xfc000]
    Traceback (most recent call last):
      File "/home/.../main.py", line 15, in <module>
        for addr, asm_instr, reil_instrs in barf.translate():
      File "/usr/local/lib/python2.7/dist-packages/barf-0.2-py2.7.egg/barf/barf.py", line 195, in translate
        for addr, asm, _ in self.disassemble(start_addr, end_addr):
      File "/usr/local/lib/python2.7/dist-packages/barf-0.2-py2.7.egg/barf/barf.py", line 217, in    disassemble
        asm = self.disassembler.disassemble(self.text_section[start:end], curr_addr)
      File "/usr/local/lib/python2.7/dist-packages/barf-0.2-py2.7.egg/barf/arch /arm/armdisassembler.py", line 203, in disassemble
        instr = self._cs_translate_insn(disasm)
      File "/usr/local/lib/python2.7/dist-packages/barf-0.2-py2.7.egg/barf/arch/arm/armdisassembler.py", line 348, in _cs_translate_insn
        operands = [self.__cs_translate_operand(op, cs_insn) for op in cs_insn.operands]
      File "/usr/lib/python2.7/dist-packages/capstone/__init__.py", line 541, in __getattr__
        raise CsError(CS_ERR_DETAIL)
     capstone.CsError: Details are unavailable (CS_ERR_DETAIL)

    Process finished with exit code 1

However, BARF runs smoothly with no problems on the toys supplied in the repo.

More Info:

 - The binary is in ARM32, mode:ARM
 - `pip list | grep capstone` -> capstone (3.0.4)
 - `python-capstone 3.0.4` is installed
 - `libcapstone3` and `libcapstone-dev` are installed
 - `PyBFD` is ok.

**Comment by neuromancer** [comment]
2016-07-12 13:25 GMT+02:00 Ali Reza Barkhordari <notifications@github.com>:

> I've installed BARF but I'm not sure if it's installed correctly. I run
> the following code for a binary shared object file (.so), but it
> encounters an error while it's translating.
>
> from barf import BARF
>
> # Open binary file.
> barf = BARF('bin/tests/test1.so')
>
> # Print assembly instruction.
> for addr, asm_instr, reil_instrs in barf.translate():
>     print("0x{addr:08x} {instr}".format(addr=addr, instr=asm_instr))
>
>     # Print REIL translation.
>     for reil_instr in reil_instrs:
>         print("{indent:11s} {instr}".format(indent="", instr=reil_instr))
>
> Output:
>
> Couldn't import dot_parser, loading of dot files will not be possible.
> 0x00000e98 moval r4, r0
>             str   [DWORD r0, EMPTY, DWORD r4]
>             and   [DWORD r0, DWORD 0xffffffff, DWORD t1]
>             bisz  [DWORD t1, EMPTY, BIT zf]
>             bsh   [DWORD r0, DWORD 0xffffffe1, DWORD t2]
>             and   [DWORD t2, DWORD 0x1, BIT t3]
>             str   [BIT t3, EMPTY, BIT nf]
> 0x00000e9a bal #0x9dc
>             jcc   [BIT 0x1, EMPTY, POINTER 0x9dc00]
> 0x00000e9c moval r0, r0
>             str   [DWORD r0, EMPTY, DWORD r0]
>             and   [DWORD r0, DWORD 0xffffffff, DWORD t4]
>             bisz  [DWORD t4, EMPTY, BIT zf]
>             bsh   [DWORD r0, DWORD 0xffffffe1, DWORD t5]
>             and   [DWORD t5, DWORD 0x1, BIT t6]
>             str   [BIT t6, EMPTY, BIT nf]
> 0x00000e9e bal #0xfc0
>             jcc   [BIT 0x1, EMPTY, POINTER 0xfc000]
> Traceback (most recent call last):
>   File "/home/.../main.py", line 15, in <module>
>     for addr, asm_instr, reil_instrs in barf.translate():
>   File "/usr/local/lib/python2.7/dist-packages/barf-0.2-py2.7.egg/barf/barf.py", line 195, in translate
>     for addr, asm, _ in self.disassemble(start_addr, end_addr):
>   File "/usr/local/lib/python2.7/dist-packages/barf-0.2-py2.7.egg/barf/barf.py", line 217, in    disassemble
>     asm = self.disassembler.disassemble(self.text_section[start:end], curr_addr)
>   File "/usr/local/lib/python2.7/dist-packages/barf-0.2-py2.7.egg/barf/arch /arm/armdisassembler.py", line 203, in disassemble
>     instr = self._cs_translate_insn(disasm)
>   File "/usr/local/lib/python2.7/dist-packages/barf-0.2-py2.7.egg/barf/arch/arm/armdisassembler.py", line 348, in _cs_translate_insn
>     operands = [self.__cs_translate_operand(op, cs_insn) for op in cs_insn.operands]
>   File "/usr/lib/python2.7/dist-packages/capstone/__init__.py", line 541, in __getattr__
>     raise CsError(CS_ERR_DETAIL)
>  capstone.CsError: Details are unavailable (CS_ERR_DETAIL)
>
>

It looks like an internal capstone error. Can you try to dissassemble using
directly capstone? (for instance:
http://www.capstone-engine.org/lang_python.html)

**Comment by abforce** [comment]
No. I've not tried this. But I don't think so, because Hopper can disassemble it very easily, and in other side Hopper internally uses Capstone as the disassembler.

My binary is not a very large object, it's just a toy `.so` file for testing purposes. I attached it: [test1.so.zip](https://github.com/programa-stic/barf-project/files/359230/test1.so.zip)

**Comment by cnheitman** [comment]
Hi! There was a step missing in the setup of Capstone. Now it's fixed. I tested it with the file you included and it worked. 

I added a parameter to the ``translate`` method. You can now pass the ``arch_mode`` in case it cannot extract it from the binary. The example looks like this (note that it only translates the first function):

```
from barf import BARF
from barf.arch import ARCH_ARM_MODE_ARM

# Open binary file.
barf = BARF('bin/tests/test1.so')

# Print assembly instruction.
for addr, asm_instr, reil_instrs in barf.translate(0x00000e98, 0x00000ed0, arch_mode=ARCH_ARM_MODE_ARM):
    print("0x{addr:08x} {instr}".format(addr=addr, instr=asm_instr))

    # Print REIL translation.
    for reil_instr in reil_instrs:
        print("{indent:11s} {instr}".format(indent="", instr=reil_instr))
```

**Comment by cnheitman** [comment]
The issue has been resolved so I'm closing it.
