### ISSUE TITLE
ARM translating mode is set to Thumb by default

### ISSUE THREAD

**Issue by abforce** [programa-stic/barf-project#34]
As far as I know, BARF currently doesn't support thumb mode, however it's set to thumb mode by default.

For ARM mode binaries, `recover_cfg` function won't work as it assumes it's thumb. In `armdisassembler.py`, the `disassembler` function is called without provision of its last argument, so it assumes it's a thumb binary and thereafter everything will be messed up.

**Comment by cnheitman** [comment]
Hi! In fact, there is basic support for thumb mode. I've made some changes so the CPU mode can be specified and avoid the problem you mentioned (I've removed the default thumb mode). Ideally, the CPU mode should be loaded automatically, however, I haven't found a way to do it yet.

Additionally, I've added two more examples ``examples/arm/recover_cfg_arm.py`` and ``examples/arm/recover_cfg_thumb.py`` so you can try the CFG recovery functionally (passing the mode as a parameter).

**Comment by abforce** [comment]
Thank you for the fix @cnheitman. I close the issue.
