### ISSUE TITLE
CFG recovery issue with noreturn functions

### ISSUE THREAD

**Issue by abforce** [programa-stic/barf-project#35]
If a `noreturn` function occurs in a function for which the CFG is being created, the traversing process isn't stopped when it encounters a `noreturn` function. After a `noreturn` function, there might be data entries (i.e. `dd`) which can't be disassembled, so this may lead to unknown behaviors.

For example in the binary file attached, in function `foo` we have a `__stack_chk_fail` function call which is `noreturn`. CFG recovery in this case goes through the next function and yields a weird graph.

Another issue is that in that function there's an instruction which _pops_ on `r15` (i.e. `pc`). In ARM, stack pop on `r15` means function return if its corresponding _push_ was `r14` (i.e. link register).

By the way, to build CFG graphs I can only supply the _start_ address and can't determine the address at which a function ends, so CFG recovery functionality should be smart enough to correctly ends at the end of a function.

[test-bin.zip](https://github.com/programa-stic/barf-project/files/374219/test-bin.zip)

**Comment by cnheitman** [comment]
Hi! I fixed both issues: a) stop when calling a ``noreturn`` function, and b) stop when popping ``r15``. The following snippet shows how to do the CFG recovery.

```python
from barf.barf import BARF
from barf.arch import ARCH_ARM_MODE_ARM

filename = "test1.so"

barf = BARF(filename)

symbols_by_addr = {
    # addr : (name, size, returns?)
    0xe50 : ("__stack_chk_fail", 0xc, False)
}

cfg = barf.recover_cfg(ea_start=0x00000edc, ea_end=0x00000ff7, symbols=symbols_by_addr, arch_mode=ARCH_ARM_MODE_ARM)

cfg.save(filename + "_cfg", print_ir=False)
```

Note two things: a) you have to "declare" which are the ``noreturn`` functions, and b) you can pass the end address of the function as a parameter of ``recover_cfg``.

**Comment by abforce** [comment]
Thank you for the fixes. Two questions:

1. What's the purpose of the size field in `(name, size, returns?)`? Why do we need this `size`?
2. Can I leave the end address parameter unfilled? Since in my project we can't determine the end address of a function, so supplying this parameter would be a bit tricking our application. (What we need is that we can obtain a complete CFG of a function given its start address.)

**Comment by cnheitman** [comment]
You're welcome! Regarding your questions:

1. It represents the size of the function (in this case, ``__stack_chk_fail``). It is not necessary to set it to a proper value (it is not used during the recovery).
2. Yes, you can leave it unfilled. I misread the last paragraph of your first comment (I thought you wanted to pass it, that's why I added it in the snippet). 

The recovery should be smart enough to do what you are trying to do, let me known in case it isn't.

**Comment by abforce** [comment]
Thank you dear @cnheitman for your time and consideration. Everything is now clear.
