### ISSUE TITLE
Support movabs

### ISSUE THREAD

**Issue by Nordwald** [programa-stic/barf-project#40]
'movabs' is a GAS specific notation adopted by capstone. It is the same Opcode as regular mov instructions, but is used to handle 64bit operands.

I've implemented rudimentary support like this:

```
    def _translate_movabs(self, tb, instruction):
        # alias for mov with 64bit operands
        self._translate_mov(tb, instruction)
```

It works well in the scenarios I tested (mostly objectiveC on x64)

**Comment by cnheitman** [comment]
Great! Do you want to send me a PR or should I apply this change directly?

**Comment by cnheitman** [comment]
I've applied the change. Thanks.
