### ISSUE TITLE
ValueError: Unknown format code 'x' for object of type 'str'

### ISSUE THREAD

**Issue by roj4s** [programa-stic/barf-project#41]
When I try recovering cfg from /bin/ls in ubuntu 16.04 I get this error:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/barf-0.3-py2.7.egg/barf/barf.py", line 299, in recover_cfg
    cfg, _ = self._recover_cfg(start=ea_start, end=ea_end, symbols=symbols, callback=callback)
  File "/usr/local/lib/python2.7/dist-packages/barf-0.3-py2.7.egg/barf/barf.py", line 349, in _recover_cfg
    name = "sub_{:x}".format(start)
ValueError: Unknown format code 'x' for object of type 'str'

Here is my code:

 from barf import BARF
b = BARF("/bin/ls")
cfg = b.recover_cfg()

**Comment by cnheitman** [comment]
Fixed (if no start address is provided it takes the entry point of the binary as the default start for the recovering). Thanks for reporting!

PS: If you want to recover the cfgs you should take a look at the [BARFcfg](https://github.com/programa-stic/barf-project/blob/master/tools/cfg/BARFcfg) tool, which was specially built for that task.
