### ISSUE TITLE
x86 recover_cfg.py fails with TypeError: unsupported operand type(s) 

### ISSUE THREAD

**Issue by OhioDuckFarmer** [programa-stic/barf-project#48]
I have just finished installing the latest version of barf and was trying the example scripts.  When I ran the recover_cfg.py script (all other x86 scripts worked) barf would error out with:

    $> cat barf.log 
    2018-04-12 10:26:45,874: barf.barf:INFO: [+] BARF: Initializing...
    2018-04-12 10:26:45,879: smtlibv2:DEBUG: >(set-option :global-decls false)
    2018-04-12 10:26:45,880: smtlibv2:DEBUG: >(set-logic QF_AUFBV)
    2018-04-12 10:26:45,880: smtlibv2:DEBUG: >(declare-fun MEM_0 () (Array (_ BitVec 64) (_ BitVec 8)))
    2018-04-12 10:26:45,884: smtlibv2:DEBUG: >(set-option :global-decls false)
    2018-04-12 10:26:45,884: smtlibv2:DEBUG: >(set-logic QF_AUFBV)
    2018-04-12 10:26:45,884: smtlibv2:DEBUG: >(declare-fun MEM_0 () (Array (_ BitVec 64) (_ BitVec 8)))
    2018-04-12 10:26:45,923: barf.analysis.basicblock.basicblock:ERROR: Failed to save basic block graph: ~/barf-project/examples/bin/x86/branch4_cfg (dot)
    Traceback (most recent call last):
      File "~/barf/local/lib/python2.7/site-packages/barf-0.2.1-py2.7.egg/barf/analysis/basicblock/basicblock.py", line 415, in save
    dot_graph.write("{}.{}".format(filename, format), format=format)
      File "build/bdist.linux-x86_64/egg/pydot.py", line 1756, in write
    s = self.create(prog, format, encoding=encoding)
      File "build/bdist.linux-x86_64/egg/pydot.py", line 1836, in create
    self.write(tmp_name, encoding=encoding)
      File "build/bdist.linux-x86_64/egg/pydot.py", line 1750, in write
    s = self.to_string()
      File "build/bdist.linux-x86_64/egg/pydot.py", line 1492, in to_string
    graph.append( node.to_string()+'\n' )
      File "build/bdist.linux-x86_64/egg/pydot.py", line 623, in to_string
    node += ' [' + node_attr + ']'
    TypeError: unsupported operand type(s) for +=: 'long' and 'str'

I am trying to run this on Ubuntu 16.04:
    Linux devlinux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cnheitman** [comment]
Hi! I've tried to reproduce the error you found but I couldn't. Did you install BARF via `pip` or download the latest release and install it through `python setup.py`?

**Comment by OhioDuckFarmer** [comment]
Since i dont remeber right now and i am not at home to double check, i will get back to you later tonight


Sent via the Samsung Galaxy S8, an AT&T 4G LTE smartphone
-------- Original message --------From: cnheitman <notifications@github.com> Date: 4/13/18  15:57  (GMT-05:00) To: programa-stic/barf-project <barf-project@noreply.github.com> Cc: OhioDuckFarmer <ohioduckfarmer@gmail.com>, Author <author@noreply.github.com> Subject: Re: [programa-stic/barf-project] x86 recover_cfg.py fails with
  TypeError: unsupported operand type(s) (#48) 
Hi! I've tried to reproduce the error you found but I couldn't. Did you install BARF via pip or download the latest release and install it through python setup.py?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/programa-stic/barf-project","title":"programa-stic/barf-project","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/programa-stic/barf-project"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cnheitman in #48: Hi! I've tried to reproduce the error you found but I couldn't. Did you install BARF via `pip` or download the latest release and install it through `python setup.py`?"}],"action":{"name":"View Issue","url":"https://github.com/programa-stic/barf-project/issues/48#issuecomment-381245277"}}}

**Comment by OhioDuckFarmer** [comment]
Looks like i used pip.  I will uninstall and will try the latest build via setup.py


Sent via the Samsung Galaxy S8, an AT&T 4G LTE smartphone
-------- Original message --------From: cnheitman <notifications@github.com> Date: 4/13/18  15:57  (GMT-05:00) To: programa-stic/barf-project <barf-project@noreply.github.com> Cc: OhioDuckFarmer <ohioduckfarmer@gmail.com>, Author <author@noreply.github.com> Subject: Re: [programa-stic/barf-project] x86 recover_cfg.py fails with
  TypeError: unsupported operand type(s) (#48) 
Hi! I've tried to reproduce the error you found but I couldn't. Did you install BARF via pip or download the latest release and install it through python setup.py?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/programa-stic/barf-project","title":"programa-stic/barf-project","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/programa-stic/barf-project"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cnheitman in #48: Hi! I've tried to reproduce the error you found but I couldn't. Did you install BARF via `pip` or download the latest release and install it through `python setup.py`?"}],"action":{"name":"View Issue","url":"https://github.com/programa-stic/barf-project/issues/48#issuecomment-381245277"}}}
