### ISSUE TITLE
Error in barf/analysis/gadgets/verifier.py

### ISSUE THREAD

**Issue by talangcc** [programa-stic/barf-project#54]
I am doing my project on the basis of BARF, and I encountered this problem.
AttributeError: 'CodeAnalyzer' object has no attribute 'get_memory_curr'.
I review the code and discover the class 'CodeAnalyzer' have the method 'get_memory' instead of 'get_memory_curr', and it can be discovered in barf/analysis/codeanalyzer/codeanalyzer.py. 
The method '_get_constrs_no_operation' in class 'GadgetVerifier' located in 122L, barf/analysis/codeanalyzer/verifier.py calls this method. The commented code in 121L seems to be correct.

**Comment by cnheitman** [comment]
I've just pushed a fix for this. Thanks for reporting!
