### ISSUE TITLE
Add minimal support for missing instructions

### ISSUE THREAD

**Issue by neuromancer** [programa-stic/barf-project#9]
I made a short list of unsopported instructions using the serial testcases, with examples:

* bt eax, edx
* movsx eax, al
* cmpxchg dword ptr [edi], ecx

These instructions (probably) should be supported to obtain correct resuts in our testcases.

**Comment by neuromancer** [comment]
An informal survey on missing instructions (made using a large number of x86 binaries from Debian) is available here:

    fstp   :3268  
    fld    :2729  
    movsx  :1276  
    fmul   :1009  
    fild   : 860  
    lock   : 677  
    fxch   : 579  
    fldcw  : 486  
    faddp  : 451  
    fadd   : 426  
    fst    : 398  
    fnstsw : 365  
    sahf   : 365  
    fistp  : 248  
    fldz   : 246  
    fdiv   : 190  
    fnstcw : 188  
    fsub   : 174  
    fucom  : 166  
    fmulp  : 143  
    fld1   : 108  
    fucompp: 102  
    fucomp :  97  
    idiv   :  97  
    fdivp  :  83  
    fsubr  :  69  
    fchs   :  66  
    fsubp  :  65  
    fdivrp :  46  
    fsubrp :  46  
    cwde   :  39  
    setle  :  29  
    fdivr  :  25  
    fsqrt  :  23  
    jnp    :  20  
    setge  :  15  
    setl   :  12  
    bswap  :   9  
    fabs   :   8  
    frndint:   7  
    cdq    :   6  
    fist   :   4  
    setnp  :   4  
    bsr    :   3  
    cli    :   1  
    das    :   1  
    in     :   1  
    insb   :   1  
    int    :   1

**Comment by zachriggle** [comment]
I'm surprised to see `movsx` on this list

**Comment by cnheitman** [comment]
Hi! That list should be updated. ``movsx`` is currently supported along with ``setcc`` and ``jnp``. Regarding FPU instructions, there's no plan to support them in the near future.

**Comment by neuromancer** [comment]
idiv seems to be a very useful instruction to support, since it is used to check some overflow constrains that we want to verify..

**Comment by cnheitman** [comment]
The most frequently used instructions has been implemented (FPU instructions are not included, there is no plan to implement them in the near future), so I'm closing this issue.
